import { OverworldMap } from './interfaces/Overworld';

export const mockMap: OverworldMap = {
	encounters: ['pikachu', 'growlithe'],
	dialogues: {
		test: { passages: ['test seems to work', 'thats great'] },
	},
	map: [
		[
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onClick: { type: 'DIALOGUE', id: 'test' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
		],
		[
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
			{ passable: true, onStep: { type: 'ENCOUNTER' } },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: false },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
		[
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
			{ passable: true },
		],
	],
};
